time_limit: 1000
memory_limit: 65535
test_cases:
  - in: data.in
    ans: data.ans
judge_type: standard
# code:
#   file: main.c
#   language: c
# code:
#   file: main.cpp
#   language: cpp
code:
  file: main.py
  language: python
# code:
#   file: main.sh
#   language: bash
