data_dir: /data
judge_dir: /tmp
rootfs: /root/river/newbie-sandbox/runtime/rootfs
cgroup: 1
languages:
  C:
    compile_cmd: /usr/bin/gcc main.c -o a.out -Wall -O2 -std=c99 --static
    code_file: main.c
    run_cmd: ./a.out
    version: gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0

  C++:
    compile_cmd: /usr/bin/g++ main.cpp -O2 -Wall --static -o a.out --std=gnu++17
    code_file: main.cpp
    run_cmd: ./a.out
    version: g++ (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0

  Python:
    compile_cmd: /usr/bin/python3.8 -m compileall main.py
    code_file: main.py
    run_cmd: /usr/bin/python3.8 main.py
    version: Python 3.8.5

  Rust:
    compile_cmd: /root/.cargo/bin/rustc main.rs -o a.out -C opt-level=2
    code_file: main.rs
    run_cmd: ./a.out
    version: rustc 1.49.0 (e1884a8e3 2020-12-29)

  JavaScript:
    compile_cmd: /usr/bin/node /plugins/node/validate.js main.js
    code_file: main.js
    run_cmd: /usr/bin/node main.js
    version: Node.js v14.15.4

  TypeScript:
    compile_cmd: /usr/bin/tsc -p /tsconfig.json
    code_file: main.ts
    run_cmd: /usr/bin/node main.js
    version: v4.1.3 (Node.js v14.15.4)

  Go:
    compile_cmd: /usr/bin/go build -o a.out -p 1 main.go
    code_file: main.go
    run_cmd: ./a.out
    version: go version go1.15.6 linux/amd64

  Java:
    compile_cmd: /usr/bin/javac Main.java
    code_file: Main.java
    run_cmd:  /usr/bin/java -Xmx8m -XX:MaxHeapSize=64m -XX:InitialHeapSize=8m -XX:CompressedClassSpaceSize=8m -XX:MaxMetaspaceSize=64m -cp . Main
    version: |-
      openjdk 11.0.9.1 2020-11-04
      OpenJDK Runtime Environment (build 11.0.9.1+1-Ubuntu-0ubuntu1.20.04)
      OpenJDK 64-Bit Server VM (build 11.0.9.1+1-Ubuntu-0ubuntu1.20.04, mixed mode, sharing)

  C#:
    compile_cmd: /usr/bin/csc main.cs
    code_file: main.cs
    run_cmd: /usr/bin/mono main.exe
    version: |-
      Mono JIT compiler version 6.12.0.122 (tarball Mon Feb 22 17:28:32 UTC 2021)
      Microsoft (R) Visual C# Compiler version 3.6.0-4.20224.5 (ec77c100)

  PHP:
    compile_cmd: php -l main.php
    code_file: main.php
    run_cmd: php -f main.php
    version: PHP 8.0.3 (cli) (built:: Mar  5 2021 07:54:13) ( NTS )

  Ruby:
    compile_cmd: ruby -c main.rb
    code_file: main.rb
    run_cmd: ruby main.rb
    version: ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux-gnu]

  Perl:
    compile_cmd: perl -c main.pl
    code_file: main.pl
    run_cmd: perl main.pl
    version: This is perl 5, version 30, subversion 0 (v5.30.0) built for x86_64-linux-gnu-thread-multi

  Haskell:
    compile_cmd: ghc main.hs
    code_file: main.hs
    run_cmd: ./main
    version: The Glorious Glasgow Haskell Compilation System, version 8.6.5

  Pascal:
    compile_cmd: fpc -omain main.p
    code_file: main.p
    run_cmd: ./main
    version: Free Pascal Compiler version 3.0.4+dfsg-23 [2019/11/25] for x86_64
